// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fit_box.Data;

#nullable disable

namespace fit_box.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240906154214_AdicionarLoginMarmitaIngredientes")]
    partial class AdicionarLoginMarmitaIngredientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fit_box.Models.Ingredientes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameIngrediente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("QuantidadeEmEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.ToTable("Ingredientes", (string)null);
                });

            modelBuilder.Entity("fit_box.Models.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Logins", (string)null);
                });

            modelBuilder.Entity("fit_box.Models.Marmita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameMarmita")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TamanhoMarmita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.ToTable("Marmitas", (string)null);
                });

            modelBuilder.Entity("fit_box.Models.MarmitaIngrediente", b =>
                {
                    b.Property<Guid>("MarmitaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeEmGramas")
                        .HasColumnType("int");

                    b.HasKey("MarmitaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("MarmitaIngredientes", (string)null);
                });

            modelBuilder.Entity("fit_box.Models.Ingredientes", b =>
                {
                    b.HasOne("fit_box.Models.Login", "Login")
                        .WithMany("Ingredientes")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("fit_box.Models.Marmita", b =>
                {
                    b.HasOne("fit_box.Models.Login", "Login")
                        .WithMany("Marmitas")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("fit_box.Models.MarmitaIngrediente", b =>
                {
                    b.HasOne("fit_box.Models.Ingredientes", "Ingrediente")
                        .WithMany()
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("fit_box.Models.Marmita", "Marmita")
                        .WithMany("MarmitaIngredientes")
                        .HasForeignKey("MarmitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Marmita");
                });

            modelBuilder.Entity("fit_box.Models.Login", b =>
                {
                    b.Navigation("Ingredientes");

                    b.Navigation("Marmitas");
                });

            modelBuilder.Entity("fit_box.Models.Marmita", b =>
                {
                    b.Navigation("MarmitaIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
